### ISSUE TITLE
Is there all elements of the matrix are within 10?

### ISSUE THREAD

**Issue by yongzhuo** [facebookresearch/LAWT#3]
Is there all elements of the matrix are within 10?

**Comment by f-charton** [comment]
By default, all coefficients of the generated matrices are uniformly sampled between -10 and 10. 

You can change this using two parameters (see src/generators.py, functions rand_matrix and gen_matrix).
--max_input_coeff: 10 by default, change it to 100 for coefficients between -100 and 100
--gaussian: False by default, set it to True and the coefficients will be sampled from a normal distribution (centred, with standard deviation max_coeff/sqrt(3), ie the same as the corresponding uniform distribution)

Additional parameters allow you to sample from different distributions (for the out of distribution experiments): 
--min_input_coeff > 0 (and <max-input_coeff) creates a mixture of uniform (or gaussian) distributions 
--eigen_distribution generates a specific dsitribution of eigenvalues (for the eigenvalue, eigenvector and symmetric inverse generators only).

**Comment by yongzhuo** [comment]
ok, thanks.
